###
POST http://localhost:3000/api/request_token
Content-Type: application/json

{
    "username" : "<your username>",
    "password" : "<your password>"
}

###
POST http://localhost:3000/api/send_message
Content-Type: application/json
Authorization: Bearer <Please Paste Response Token Here !>

{
    "to" : "62xxxxxxxxx",
    "text" : "😂 😂 😂 😂 😂 "
}

